// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://sbkmwkwvqsuoowsdrtwz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNia213a3d2cXN1b293c2RydHd6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc4ODI1OTksImV4cCI6MjA3MzQ1ODU5OX0.UjRjTlJ9IQoo8mdkO_7VcajSS7ZW4uDU6umPBdHxCHc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});